---
apiVersion: v1
kind: Secret
metadata:
  name: seedgen
  namespace: openshift-lifecycle-agent
type: Opaque
data:
  seedAuth: ${SEED_AUTH}
  # hubKubeconfig: ${HUB_KUBECONFIG}

---
apiVersion: lca.openshift.io/v1alpha1
kind: SeedGenerator
metadata:
  name: seedimage
spec:
  seedImage: ${SEED_IMAGE}
  # recertImage: ${RECERT_IMAGE}
