#!/bin/bash
export IP="192.168.127.10"
export BASE_RESOLV_CONF=/run/NetworkManager/resolv.conf
if [ "$2" = "dhcp4-change" ] || [ "$2" = "dhcp6-change" ] || [ "$2" = "up" ] || [ "$2" = "connectivity-change" ]; then
	export TMP_FILE=$(mktemp /etc/forcedns_resolv.conf.XXXXXX)
	cp  $BASE_RESOLV_CONF $TMP_FILE
	chmod --reference=$BASE_RESOLV_CONF $TMP_FILE
	sed -i -e "s/test-cluster.redhat.com//" \
	-e "s/search /& test-cluster.redhat.com /" \
	-e "0,/nameserver/s/nameserver/& $IP\n&/" $TMP_FILE
	mv $TMP_FILE /etc/resolv.conf
fi